/* --------------------------------------------------------------------------------
 #
 #	4DPlugin-Window-Placement.h
 #	source generated by 4D Plugin Wizard
 #	Project : Window Placement
 #	author : miyako
 #	2019/07/29
 #  
 # --------------------------------------------------------------------------------*/

#ifndef PLUGIN_WINDOW_PLACEMENT_H
#define PLUGIN_WINDOW_PLACEMENT_H

#include "4DPlugin-JSON.h"
#include "4DPluginAPI.h"

#pragma mark -

void SET_WINDOW_PLACEMENT(PA_PluginParameters params);
void Get_window_placement(PA_PluginParameters params);

#endif /* PLUGIN_WINDOW_PLACEMENT_H */
